server:
  port: 8822
  context-path: /
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaltZone: http://peer1:8761/eureka/
spring:
  application:
    name: ribbon-eureka-client
#stores:
#  ribbon:
#    listOfServers: www.baidu.com,www.google.com
#ribbon:
#  eureka:
#    enabled: false
    name: eureka-client